CREATE DATABASE db_try;
USE db_try;
CREATE TABLE tri(
  user_id INT AUTO_INCREMENT PRIMARY KEY;
  user VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  mot_de_passe VARCHAR(255) NOT NULL);
